### PR TITLE
Add first stardoc API docgen target

### PR DESCRIPTION
**Pull request by alexeagle**
See #468

### CODE REVIEW

**Review by keith — APPROVED** [review]
did you want to add something more to this?

**Comment by keith** [comment]
ah looks like the tests reveal some issues

**Comment by alexeagle** [comment]
Hmm, interesting despite all my usual tricks, stardoc fails when running on CI due to inability to locate our self-references. It does run locally so I will make a follow-up change to get the tests running. At least in the meantime it's an improvement that you have a generator hooked up.

**Comment by alexeagle** [comment]
CI failure seems to be pre-existing

**Pull request merged**
