### PR TITLE
Reformat all .bzl files to 80 columns and make doc comments consistent (4-space indent under Args/Returns, 4 characters between start of list bullet/number and list item text, use backslash after leading triple-quote in doc attributes to remove an unnecessary line break).

### PR DESCRIPTION
**Pull request by swiple-rules-gardener**
Reformat all .bzl files to 80 columns and make doc comments consistent (4-space indent under Args/Returns, 4 characters between start of list bullet/number and list item text, use backslash after leading triple-quote in doc attributes to remove an unnecessary line break).

### CODE REVIEW

**Comment by kastiglione** [comment]
what tool did all this?

**Comment by kastiglione** [comment]
Is this a bazelbuild-wide undertaking?

**Comment by allevato** [comment]
> what tool did all this?

These two hands 🙌 , followed by buildifier to clean up anything I might have screwed up.

> Is this a bazelbuild-wide undertaking?

No, I've been annoyed by the inconsistency that's slowly crept into the code base for a while. I'd occasionally do some cleanup opportunistically in other changes, but it was a slow day, so I finally decided to just get it done.

**Comment by kastiglione** [comment]
haha when I said "tool" it did cross my mind that might sound funny if it was manually done

good to know, thanks!

**Pull request merged**
