### PR TITLE
Update Travis CI to use Bazel 0.17.2, and protobuf dependency to v3.6.1

### PR DESCRIPTION
**Pull request by kastiglione**
Update Travis to use Bazel 0.17.2. In addition, update protobuf dependency to latest version, v3.6.1.

### CODE REVIEW

**Comment by kastiglione** [comment]
Should (can) `SWIFT_VERSION` be updated to 4.2 for Linux builds?

**Comment by kastiglione** [comment]
```
ERROR: /private/var/tmp/_bazel_travis/87bc3211861d35c3817d8415281b400b/external/com_google_protobuf/BUILD:274:1: undeclared inclusion(s) in rule '@com_google_protobuf//:protoc_lib':
this rule is missing dependency declarations for the following files included by 'external/com_google_protobuf/src/google/protobuf/compiler/java/java_doc_comment.cc':
  '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdlib.h'
  [many more from MacOSX.sdk] ...
```

**Comment by allevato** [comment]
Any idea what might have caused this? I'm running 0.17.2 and Xcode 10 on my dev machine and I'm not seeing those errors; it builds correctly for me.

But it's interesting that the error message indicates that it's looking for headers in the CommandLineTools directory instead of some directory of /Applications/Xcode.app/Contents/Developer.

**Comment by kastiglione** [comment]
I don't know, no. My local build gets a lot of warnings, mostly all:

> ld: warning: object file (bazel-out/darwin_x86_64-fastbuild/bin/foo/libBar.a(File.swift.o)) was built for newer OSX version (10.14) than being linked (10.13)

**Comment by sergiocampama** [comment]
I wonder if the travis setup needs to have `xcode select -s /Applications/Xcode.app`

**Comment by kastiglione** [comment]
Good idea, I can try that.

**Comment by kastiglione** [comment]
Everything looks right:

```
xcode-select --print-path
/Applications/Xcode-10.0.app/Contents/Developer

xcrun -sdk macosx --show-sdk-path
/Applications/Xcode-10.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk
```

**Comment by kastiglione** [comment]
@allevato for testing

**Comment by kastiglione** [comment]
Is there a way to log the value for `__BAZEL_XCODE_SDKROOT__`?

**Comment by kastiglione** [comment]
1. The target that fails is `@com_google_protobuf//:js_embed`.
2. `js_embed` was removed from protobuf as of protocolbuffers/protobuf#4709 which is in [v3.6.1](https://github.com/protocolbuffers/protobuf/commit/b3e4e3abe0d2f79ec9f1e4e24e12dc642d662546)
3. rules_swift is using v3.5.1, which has the comment "latest as of 2018-01-11"

Should/can rules_swift update its protobuf dependency?

**Comment by kastiglione** [comment]
Same problem, this time a different target in protobuf: `@com_google_protobuf//:protoc`

**Comment by kastiglione** [comment]
Something is up with the command line tools. There are a number of recent related issues:

* bazelbuild/bazel#6144
* bazelbuild/bazel#6195
* bazelbuild/bazel#6240

In particular, https://github.com/bazelbuild/bazel/issues/6144#issuecomment-422417756:

> I installed the [command line tools for Xcode 10 / macOS 10.13.6 DMG](
https://download.developer.apple.com/Developer_Tools/Command_Line_Tools_macOS_10.13_for_Xcode_10/Command_Line_Tools_macOS_10.13_for_Xcode_10.dmg) in addition and it's all good now. Perhaps related to changes in packaging in preparation for 10.14. I'll note this only works if the command line tools are installed from this disk image package. If I do `xcode-select --install` then it's still broken as above.

**Comment by kastiglione** [comment]
The problem is the clang compiler is being invoked with `-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk`. Now to figure out why. It does get the right `-resource-dir` in the Xcode toolchain, so not sure why `-isysroot` whack.

**Comment by kastiglione** [comment]
`APPLE_SDK_PLATFORM` and `APPLE_SDK_VERSION_OVERRIDE` are empty when building.

```
SUBCOMMAND: # @com_google_protobuf//:protoc [action 'Compiling external/com_google_protobuf/src/google/protobuf/compiler/main.cc [for host]']
(cd /private/var/tmp/_bazel_travis/87bc3211861d35c3817d8415281b400b/execroot/build_bazel_rules_swift && \
  exec env - \
    APPLE_SDK_PLATFORM='' \
    APPLE_SDK_VERSION_OVERRIDE='' \
    PATH=/Users/travis/.rvm/gems/ruby-2.4.3/bin:/Users/travis/.rvm/gems/ruby-2.4.3@global/bin:/Users/travis/.rvm/rubies/ruby-2.4.3/bin:/Users/travis/.rvm/bin:/Users/travis/bin:/Users/travis/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin \
    XCODE_VERSION_OVERRIDE=10.0.0 \
  external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++11' -iquote external/com_google_protobuf -iquote bazel-out/host/genfiles/external/com_google_protobuf -iquote bazel-out/host/bin/external/com_google_protobuf -iquote external/bazel_tools -iquote bazel-out/host/genfiles/external/bazel_tools -iquote bazel-out/host/bin/external/bazel_tools -isystem external/com_google_protobuf/src -isystem bazel-out/host/genfiles/external/com_google_protobuf/src -isystem bazel-out/host/bin/external/com_google_protobuf/src -MD -MF bazel-out/host/bin/external/com_google_protobuf/_objs/protoc/main.d '-frandom-seed=bazel-out/host/bin/external/com_google_protobuf/_objs/protoc/main.o' -isysroot __BAZEL_XCODE_SDKROOT__ -g0 -g0 -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/com_google_protobuf/src/google/protobuf/compiler/main.cc -o bazel-out/host/bin/external/com_google_protobuf/_objs/protoc/main.o)
```

**Comment by kastiglione** [comment]
The empty values for `APPLE_SDK_PLATFORM` and `APPLE_SDK_VERSION_OVERRIDE` may be a red herring, because that's the case for local builds too, which succeed.

**Comment by allevato** [comment]
Thanks for doing such a deep dive into this. It's frustrating that the upgrade is so painful.

I'd be fine with a Bazel + protobuf only update for now. Let me know when the PR is in a state that you're happy with and I'll squash it.

**Comment by kastiglione** [comment]
Thank,s yeah I wanted to figure it out. It's in a mergeable state, just bazel and protobuf version updates.

**Comment by kastiglione** [comment]
Replaced by #92.

**Pull request closed without merging**
