### PR TITLE
Use `progress_message` placeholders for more performant rules

### PR DESCRIPTION
**Pull request by thii**
From a tip in a BazelCon talk today.

### CODE REVIEW

**Comment by brentleyjones** [comment]
This only works on 5.0+, correct?

**Comment by allevato** [comment]
FWIW, this changes the message so that it prints the target label instead of the Swift module name; whether that's an improvement or not is debatable.

I also doubt that anyone has Swift builds so large that you'd see measurable memory improvements out of this; the real users who benefit are rules like C++ which create an action per _source file_ (vs. per _target_).

It would be nicer if they gave Starlark an API as rich as the native Bazel one, which would let us separate the constant part of the format string from the placeholder substitution, but still use the module name instead of one of the blessed label/input/output values. I would wait for something like that before jumping on this.

**Comment by thii** [comment]
> This only works on 5.0+, correct?

Yes this was added recently, only available since 5.0.

> FWIW, this changes the message so that it prints the target label instead of the Swift module name; whether that's an improvement or not is debatable.

I was aware about this limitation. I personally think that printing the target label would be more informative than printing just the Swift module name, especially when it comes from an external repository:

```
    Compiling Swift module @com_github_apple_swift_protobuf//:SwiftProtobuf; 2s local
```

**Comment by brentleyjones** [comment]
>I personally think that printing the target label would be more informative than printing just the Swift module name, especially when it comes from an external repository

💯

**Comment by allevato** [comment]
> I personally think that printing the target label would be more informative than printing just the Swift module name, especially when it comes from an external repository

That's reasonable!

**Review by brentleyjones — APPROVED** [review]
Now that we are targeting 5.0, this is safe to go in.

**Pull request merged**
