### PR TITLE
Switch the Swift rules over to toolchains

### PR DESCRIPTION
**Pull request by brentleyjones**
PiperOrigin-RevId: 503982850
(cherry picked from commit c42aad205d457f6fede1da7ab245800d3ec76641)

### CODE REVIEW

**Review by luispadron — APPROVED** [review]

**Comment by brentleyjones** [comment]
I need to add toolchains as well. Not sure if this is a breaking change. I know for rules_apple to be able to use this they need to update a couple call sites. But since we are still sticking the toolchain in an attribute, I believe the old ways continue to work. 

Maybe it can get odd in mixed non-toolchain/toolchain scenarios? I guess wondering if we need to bump the compatibility version again for this change (I hope not).

**Comment by brentleyjones** [comment]
Without changing anything in rules_apple, this change + #1321 + registering the toolchains still works for me locally.

**Comment by brentleyjones** [comment]
Will merge #1323 first.

**Comment by brentleyjones** [comment]
This change passes our CI, so it's probably safe without bumping our compatibility version.

**Pull request merged**
