### PR TITLE
Add support for Swift Macros

### PR DESCRIPTION
**Pull request by keith**

### CODE REVIEW

**Comment by keith** [comment]
hrm what's your build command? can you make sure you're on the latest commit here too?

**Comment by chiragramani** [comment]
> hrm what's your build command? can you make sure you're on the latest commit here too?
Yes, on the latest commit.
```
commit 3674f6fc27877af848cf55e10045587c6ac950ce (HEAD -> macro_test, origin/ks/add-support-for-swift-macros)
Author: Keith Smiley <keithbsmiley@gmail.com>
Date:   Wed Jun 14 16:41:11 2023 -0700

    Add test target example
```

Build command: building the main binary. 
```
bazel build :main
```

**Comment by keith** [comment]
Could you be using an old version of Xcode / Swift?

**Comment by keith** [comment]
(that's the same error CI has for an old version)

**Comment by chiragramani** [comment]
> Could you be using an old version of Xcode / Swift?
Oh yes, you are right, Xcode was switched, sorry for the wrong call. Works all great now!

**Comment by jafara** [comment]
whats the status of landing this?

**Comment by keith** [comment]
I think we'll likely wait a bit longer, maybe 1 more beta? to make sure things still work

**Comment by tinder-tannerbennett** [comment]
@keith Everything still working with the latest betas? 😄

**Comment by brentleyjones** [comment]
I believe an updated version of https://github.com/bazelbuild/rules_swift/pull/1061 is what will eventually land.

**Comment by keith** [comment]
https://github.com/bazelbuild/rules_swift/pull/1061

**Pull request closed without merging**
