### PR TITLE
Add platform_mappings

### PR DESCRIPTION
**Pull request by comius**
This makes it possible to use C++ toolchains with rules_swift.

### CODE REVIEW

**Comment by comius** [comment]
Blocked on: https://github.com/bazelbuild/bazel/issues/17127

**Comment by keith** [comment]
in the meantime we can probably either duplicate everything in the platform_mappings file to use the bzlmod identifier, or specify a different `--platforms_mappings=` with our bzlmod config on CI

**Comment by comius** [comment]
> in the meantime we can probably either duplicate everything in the platform_mappings file to use the bzlmod identifier

I tried using @apple_support in `platform_mapping` and even removing `repo_name` from MODULE.bazel and it just doesn't work

> or specify a different --platforms_mappings= with our bzlmod config on CI

that I can do

**Comment by comius** [comment]
Done

**Comment by keith** [comment]
erm won't we need it to have content to support the other changes you're making in this job?

**Comment by comius** [comment]
> erm won't we need it to have content to support the other changes you're making in this job?

Sorry I’m not following. I’m just adding plaform mappings from rules_apple and disabling temporary for bzlmod. What other changes?

**Comment by keith** [comment]
i mean are we going to have to un-disable for bzlmod very soon after you land https://github.com/bazelbuild/bazel/pull/19441?

**Comment by comius** [comment]
> i mean are we going to have to un-disable for bzlmod very soon after you land [bazelbuild/bazel#19441](https://github.com/bazelbuild/bazel/pull/19441)?

Correct. Yesterday I didn’t know it will be fixed so quickly. You can either merge this and I prepare a second pr, or I revert this one back to the old form. Whatever you prefer.

**Pull request closed without merging**
