### PR TITLE
Add `aspect_hints` feature

### PR DESCRIPTION
**Pull request by keith**
This includes all the upstream commits related to this, which is blocked on bazel's default for this feature

### CODE REVIEW

**Review by brentleyjones — DISMISSED** [review]

**Comment by keith** [comment]
blocked on 5.x

**Comment by brentleyjones** [comment]
https://github.com/bazelbuild/bazel/commit/47bd65adf6fd968c9eb84f96044050d852750d62

**Comment by thii** [comment]
Many other changes rely on this now. Let's enable the flag and mention about this requirement in the release notes.

**Comment by brentleyjones** [comment]
I'm not sure we want to force that flag on all users of rules_swift. Let's see if @allevato has any additional thoughts.

**Comment by allevato** [comment]
> I'm not sure we want to force that flag on all users of rules_swift. Let's see if @allevato has any additional thoughts.

The only real advice I can offer is to bring up to the Bazel team the difficulty the experimental nature of the feature poses to integrating upstream rules_swift changes (especially as they stack on each other). Unfortunately the decision to make the flag experimental in Bazel was made some time after the feature was implemented and the Swift rules had started adopting it...

**Comment by luispadron** [comment]
Dang i think this is blocking cherry-picking https://github.com/bazelbuild/rules_swift/commit/bfcae19af93924651911e6bdc669608e9453a774 as well.

**Pull request closed without merging**
